# Generated by Django 3.0.7 on 2020-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
